FROM centos:7
MAINTAINER chenleji@gmail.com

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY $GOPATH/src/github.com/chenleji/go-project-templ/go-project-templ /

ENTRYPOINT /go-project-tmpl

